#!/bin/sh

# Usage
# ./getPubRooms chat.example.com
# https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-publicrooms
#
# Notes
# Must specify a user agent for this one:
# https://github.com/matrix-org/python-canonicaljson/issues/33

. ../credentials

getPubRooms() {
    curl -A 'Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' \
         -H "Authorization: Bearer $accessToken" \
         -X GET 'https://'"$1":"$matrixServerPort"'/_matrix/client/r0/publicRooms' | jq -r
}
getPubRooms "$1"
