#!/bin/sh

# Usage
# ./getVersion chat.example.com
# https://matrix.org/docs/spec/client_server/latest#get-matrix-client-versions

. ../credentials

getVersion() {
    curl -X GET 'https://'"$1":"$matrixServerPort"'/_matrix/federation/v1/version'
}
getVersion "$1"
