#!/bin/sh

# Usage
# ./kickUsers chat.example.com roomid:example.com
# https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-kick

. ../credentials
exclude=""

getUsers() {
    curl -A 'Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' \
         -H "Authorization: Bearer $accessToken" \
         -X GET 'https://'"$1":"$matrixServerPort"'/_matrix/client/r0/rooms/%21'"$2"'/members?&membership=join&not_membership=leave' |
         jq -r --arg ex $exclude '.chunk[] | select(.sender != $ex) | .sender'
     }
users=$(getUsers)

kickUsers() {
    for user in $users; do
        echo "$user"
        curl -A 'Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' \
             -H "Authorization: Bearer $accessToken" \
             -H "Content-Type: application/json" \
             --data '{"reason":"Old room, see #privacyguides-lounge:matrix.org","user_id":"'"$user"'"}' \
             -X POST 'https://'"$1":"$matrixServerPort"'/_matrix/client/r0/rooms/%21'"$2"'/kick' | jq -r
    done
}
kickUsers
