#!/bin/sh

# Usage
# ./leave chat.example.com roomid:example.com
# https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-leave

. ../credentials

leave() {
   curl -A 'Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' \
        -H "Authorization: Bearer $accessToken" \
        -X POST 'https://'"$1":"$matrixServerPort"'/_matrix/client/r0/rooms/%21'"$2"'/leave'
}
leave "$1" "$2"
