#!/bin/sh

# Usage
# ./listUserMembership @user:example.com
# https://github.com/matrix-org/synapse/blob/v1.24.0/docs/admin_api/user_admin_api.rst#list-room-memberships-of-an-user

. ../credentials

listUserMembership() {
    curl -H "Authorization: Bearer $accessToken" \
         -X GET 'https://'"$matrixServer":"$matrixServerPort"'/_synapse/admin/v1/users/%40'"$1"'/joined_rooms'
}
listUserMembership "$1"
